# Generated by Django 5.2.6 on 2025-09-21 00:45

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ScheduledJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("job_id", models.CharField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("function_name", models.CharField(max_length=100)),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[
                            ("interval", "Interval"),
                            ("cron", "Cron"),
                            ("date", "Date"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "trigger_config",
                    models.JSONField(help_text="Trigger configuration as JSON"),
                ),
                ("is_enabled", models.BooleanField(default=True)),
                ("last_run", models.DateTimeField(blank=True, null=True)),
                ("next_run", models.DateTimeField(blank=True, null=True)),
                ("run_count", models.PositiveIntegerField(default=0)),
            ],
            options={
                "db_table": "scheduled_jobs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="JobExecutionLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("job_id", models.CharField(db_index=True, max_length=100)),
                ("job_name", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RUNNING", "Running"),
                            ("SUCCESS", "Success"),
                            ("FAILED", "Failed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("duration_seconds", models.FloatField(blank=True, null=True)),
                ("result", models.JSONField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "job_execution_logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["job_id", "status"],
                        name="job_executi_job_id_f69b0e_idx",
                    ),
                    models.Index(
                        fields=["status", "created_at"],
                        name="job_executi_status_222d6e_idx",
                    ),
                ],
            },
        ),
    ]
