# Generated by Django 5.2.6 on 2025-09-21 12:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="JobExecutionLog",
        ),
        migrations.DeleteModel(
            name="ScheduledJob",
        ),
    ]
